### ISSUE TITLE
Requirements missing pyproj

### ISSUE THREAD

**Issue by micahjohnson150** [USDA-ARS-NWRC/weather_forecast_retrieval#3]
* Python version: 3.6

### Description

Install this for the first time, I attempted to 

`pip install -r requirements.txt `

and found the pygrib uses pyproj but doesn't include its requirements. 

Manual install fixes it, conversley we may want to look to see if pygrib has another version with it updated. Currently we are using 2.0.2
### What I Did

```
Collecting pygrib==2.0.2 (from -r requirements_dev.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/3c/16/d128a64f2f5e9f776d6e080ba62551b5d103a4c0acb283204135bd23f14e/pygrib-2.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-5k8065n9/pygrib/setup.py", line 18, in <module>
        import pyproj
    ModuleNotFoundError: No module named 'pyproj'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5k8065n9/pygrib/setup.py", line 21, in <module>
        from mpl_toolkits.basemap import pyproj
    ModuleNotFoundError: No module named 'mpl_toolkits.basemap'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5k8065n9/pygrib/setup.py", line 23, in <module>
        raise ImportError("either pyproj or basemap required")
    ImportError: either pyproj or basemap required

```

**Comment by micahjohnson150** [comment]
Just kidding my repo locally was farther behind than I thought. Issue resolved. Sorry, closing
